{% set version = "0.4.0" %}
{% set build = 0 %}
{% set name = "pymartini" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9edf24d812fe79814a862dfec641d600f034da777fb06cf4234c8735a3d58624

build:
  number: 0
  skip: true  # [py<36] [python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - cython
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pymartini

about:
  home: https://github.com/kylebarron/pymartini
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Cython port of Martini for fast RTIN terrain mesh generation
  description: |
    A Cython port of Martini for fast RTIN terrain mesh generation, 2-3x faster than Martini in Node.
    The only dependency is Numpy.
  doc_url: https://github.com/kylebarron/pymartini
  dev_url: https://github.com/kylebarron/pymartini

extra:
  recipe-maintainers:
    - davidbrochart
    - kylebarron
